# Generated by Django 3.2.3 on 2023-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
    ]
