# Generated by Django 3.2.3 on 2023-11-09 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20231109_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_cart',
            new_name='ShoppingСart',
        ),
    ]
