# Generated by Django 3.2.3 on 2023-10-06 13:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231006_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цветовой код'),
        ),
    ]
