# Generated by Django 3.2.3 on 2023-11-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231121_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingсart',
            options={'verbose_name': 'Cписок покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
