# Generated by Django 3.2.3 on 2023-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredientamount_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Укажите количество ингредиента', verbose_name='Количество ингредиента'),
        ),
    ]
