# Generated by Django 3.2.3 on 2023-10-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='recipes_count',
        ),
    ]
